# TODO:
# settings for liveagent
BASE_URL = "https://mechanigo.ladesk.com/api/v3"
THROTTLE_DELAY = 0.4
MAX_CONCURRENT_REQUESTS = 15
LIVEAGENT_API_MAX_PAGES = 5
LIVEAGENT_MGO_SYSTEM_USER_ID = "system00"
LIVEAGENT_MGO_SPECIAL_USER_ID = "00054iwg"
CONCURRENT_LIMIT = 15