from google.cloud.bigquery import SchemaField

TICKETS_SCHEMA = [
    SchemaField("id", "STRING"),
    SchemaField("owner_contactid", "STRING"),
    SchemaField("owner_email", "STRING"),
    SchemaField("owner_name", "STRING"),
    SchemaField("departmentid", "STRING"),
    SchemaField("agentid", "STRING"),
    SchemaField("status", "STRING"),
    SchemaField("tags", "STRING"),
    SchemaField("code", "STRING"),
    SchemaField("channel_type", "STRING"),
    SchemaField("date_created", "DATETIME"),
    SchemaField("date_changed", "DATETIME"),
    SchemaField("date_resolved", "DATETIME"),
    SchemaField("last_activity", "DATETIME"),
    SchemaField("last_activity_public", "DATETIME"),
    SchemaField("public_access_urlcode", "STRING"),
    SchemaField("subject", "STRING"),
    SchemaField("custom_fields", "STRING"),
    SchemaField("date_due", "DATETIME"),
    SchemaField("date_deleted", "DATETIME"),
    SchemaField("datetime_extracted", "DATETIME"),
]

MESSAGES_SCHEMA = [
    SchemaField("ticket_id", "STRING", mode="NULLABLE"),
    SchemaField("owner_name", "STRING", mode="NULLABLE"),
    SchemaField("agentid", "STRING", mode="NULLABLE"),
    SchemaField("agent_name", "STRING", mode="NULLABLE"),
    SchemaField("id", "STRING", mode="NULLABLE"),
    SchemaField("parent_id", "STRING", mode="NULLABLE"),
    SchemaField("userid", "STRING", mode="NULLABLE"),
    SchemaField("user_full_name", "STRING", mode="NULLABLE"),
    SchemaField("type", "STRING", mode="NULLABLE"),
    SchemaField("status", "STRING", mode="NULLABLE"),
    SchemaField("datecreated", "DATETIME", mode="NULLABLE"),
    SchemaField("datefinished", "DATETIME", mode="NULLABLE"),
    SchemaField("sort_order", "INTEGER", mode="NULLABLE"),
    SchemaField("mail_msg_id", "STRING", mode="NULLABLE"),
    SchemaField("pop3_msg_id", "STRING", mode="NULLABLE"),
    SchemaField("message_id", "STRING", mode="NULLABLE"),
    SchemaField("message_userid", "STRING", mode="NULLABLE"),
    SchemaField("message_type", "STRING", mode="NULLABLE"),
    SchemaField("message_datecreated", "DATETIME", mode="NULLABLE"),
    SchemaField("message_format", "STRING", mode="NULLABLE"),
    SchemaField("message", "STRING", mode="NULLABLE"),
    SchemaField("message_visibility", "STRING", mode="NULLABLE"),
    SchemaField("reference_code", "STRING", mode="NULLABLE"),
    SchemaField("sender_name", "STRING", mode="NULLABLE"),
    SchemaField("sender_type", "STRING", mode="NULLABLE"),
    SchemaField("receiver_name", "STRING", mode="NULLABLE"),
    SchemaField("receiver_type", "STRING", mode="NULLABLE"),
    SchemaField("datetime_extracted", "DATETIME", mode="NULLABLE"),
]

AGENTS_SCHEMA = [
    SchemaField("id", "STRING", "NULLABLE"),
    SchemaField("name", "STRING", "NULLABLE"),
    SchemaField("email", "STRING", "NULLABLE"),
    SchemaField("role", "STRING", "NULLABLE"),
    SchemaField("roleId", "STRING", "NULLABLE"),
    SchemaField("avatar_url", "STRING", "NULLABLE"),
    SchemaField("online_status", "STRING", "NULLABLE"),
    SchemaField("status", "STRING", "NULLABLE"),
    SchemaField("gender", "STRING", "NULLABLE"),
    SchemaField("last_pwd_change", "DATETIME", "NULLABLE"),
    SchemaField("twofactor_auth", "STRING", "NULLABLE"),
    SchemaField("voice_status", "STRING", "NULLABLE"),
    SchemaField("sip_phone_id", "STRING", "NULLABLE"),
    SchemaField("api_phone_id", "STRING", "NULLABLE"),
]

TAGS_SCHEMA = [
    SchemaField("id", "STRING", "NULLABLE"),
    SchemaField("name", "STRING", "NULLABLE"),
    SchemaField("color", "STRING", "NULLABLE"),
    SchemaField("background_color", "STRING", "NULLABLE"),
    SchemaField("is_public", "STRING", "NULLABLE"),
    SchemaField("is_archived", "STRING", "NULLABLE")
]